networks:
  toduo-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend-maven-cache:
  redis_data:


services:
  # * _______________________ NGINX _______________________
  nginx-dev:
    container_name: toduo_nginx_dev
    image: nginx:stable-alpine

    environment:
      - NGINX_MODE=development

    volumes:
      - './nginx/nginx.dev.conf:/etc/nginx/nginx.conf'

    networks:
      - toduo-network

    ports:
      - "80:80"

    depends_on:
      - frontend-dev
      - backend-dev
  # * _____________________ ###### _________________________



  # * _______________________ DATABASE POSTGRESQL _______________________
  db:
    container_name: toduo_db
    hostname: toduo_db

    image: postgres:18-alpine

    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3

    networks:
      - toduo-network

    ports:
      # Проброс 5433, чтобы он не конфликтовал с локальной бд
      - "5433:5432"
  # * _____________________ ###### _________________________


  # * _______________________ REDIS _______________________
  redis:
    image: redis:7.2-alpine
    container_name: toduo_redis
    hostname: toduo_redis

    networks:
      - toduo-network

    ports:
      - "6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes
  # * _____________________ ###### _________________________



  # * _______________________ BACK _______________________
  backend-dev:
    container_name: toduo_backend_dev
    hostname: toduo_backend

    image: eclipse-temurin:21-jdk-jammy
    working_dir: /app

    volumes:
      - ./backend:/app
      - backend-maven-cache:/root/.m2

    env_file:
      - .env

    environment:
      DATABASE_HOST: jdbc:postgresql://toduo_db:5432/${DATABASE_NAME}
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DEVTOOLS_RESTART_ENABLED: true
      MAVEN_CONFIG: /root/.m2

      REDIS_HOST: toduo_redis
      REDIS_PORT: 6379

    networks:
      - toduo-network
    ports:
      - "8080:8080"
      - "5005:5005"

    command: >
      ./mvnw spring-boot:run
      -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      -Dmaven.repo.local=/root/.m2/repository
  # * _____________________ ###### _________________________




  # * _______________________ FRONT _______________________
  frontend-dev:
    container_name: toduo_frontend_dev
    hostname: toduo_frontend

    environment:
      NODE_ENV: development
      VITE_WS_HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true

    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development

    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

    networks:
      - toduo-network

    ports:
      - "5173:5173"
  # * _____________________ ###### _________________________
