# * _________________________________________
# * | Development stage
FROM node:22-alpine AS development

# Workdir management
WORKDIR /app
COPY package*.json ./

COPY . .

# Build
RUN npm install


EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

# * |________________________________________



# * _________________________________________
# * | Build stage
# FROM node:22-alpine AS build

# WORKDIR /app
# COPY package*.json ./

# COPY . .

# RUN npm ci --legacy-peer-deps


# RUN npm run build


# FROM nginx:stable-alpine AS production

# COPY --from=build /app/dist /usr/share/nginx/html
# COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE 3000

# * |________________________________________